### ISSUE TITLE
update modules to make subnets, availability zones, and similar more dynamic

### ISSUE THREAD

**Issue by ketzacoatl** [fpco/fpco-terraform-aws#16]
This project pre-dates quite a few of Terraform's features that support dynamic modules, and the original modules (`asg`, `cluster-network`, `consul-cluster`, and related, in particular), ought to be updated to make use of these features. As part of this, we should also evaluate all modules using string-lists to see if that can be avoided.

**Comment by ketzacoatl** [comment]
The `asg` module, and the other modules which use `asg`, have all been updated to be more flexible, and to drop use of string-lists. The `cluster-network` and `consul-cluster` modules could use other updates, so I will leave this ticket open.

**Comment by kerscher** [comment]
Can we maybe break this into different issues for each kind of change?

**Comment by ketzacoatl** [comment]
I hit up the changes I wanted just a couple of weeks ago, and those changes are on `master`. I think we close this as complete.
